# PostgreSQL / Neon database
spring.datasource.url=jdbc:postgresql://ep-twilight-cell-agwysucr-pooler.c-2.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aPDlj8coYmB0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server:
address: 192.168.1.33
port: 8080

